# -*- coding: utf-8 -*-
"""MLOne_GithubDemo_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/AIEdX/MLOne-Basic/blob/master/Lesson/Lesson3/Demo/MLOne_GithubDemo_.ipynb
"""

#@title Copyright 2020 AIEDX. Double-click here for license information.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""#  <font color='Orange' size="33" type="Arial Black">ML-</font><font color='blue' font-backgroun="red" size='33'>O</Font><font color='Orange' size='33'>ne</font> <font color="grey" size='3'> Powered by AIEdX</font>


<img src="https://storage.googleapis.com/aiedx-public/AIEDX_logo%20-Favicon.jpg" height="80" width="80">


## Tier 1 Basic

###Lesson 3: Chocolate Chip Muffin

<img src="https://storage.googleapis.com/aiedx-public/muffin-Art.png" height="60" width="60">

# I am on github but I can come to colab if you type below command

# Example of Latex

Latex/ MathJax
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}
"""